export const imagePaths = {
  logo: require('../../assets/images/logo.png'),
  Individual: require('../../assets/images/Individual.png'),
  Buisness: require('../../assets/images/Buisness.png'),
  check: require('../../assets/images/check.png'),
  google: require('../../assets/images/google.png'),
  apple: require('../../assets/images/Apple.png'),
  warn: require('../../assets/images/warn.png'),
  graphic: require('../../assets/images/graphic.png'),
  ob1: require('../../assets/images/ob1.png'),
  ob2: require('../../assets/images/ob2.png'),
  ob3: require('../../assets/images/ob3.png'),
};

export const iconPaths = {
  moneyBag: require('../../assets/icons/money-bag.png'),
  dining: require('../../assets/icons/dining.png'),
  shopping: require('../../assets/icons/shopping.png'),
  subscriptions: require('../../assets/icons/subscriptions.png'),
  user: require('../../assets/icons/user.png'),
  userFilled: require('../../assets/icons/user-filled.png'),
  graph: require('../../assets/icons/graph.png'),
  graphFilled: require('../../assets/icons/graph-filled.png'),
  wallet: require('../../assets/icons/wallet.png'),
  walletFilled: require('../../assets/icons/wallet-filled.png'),
  home: require('../../assets/icons/home.png'),
  homeFilled: require('../../assets/icons/home-filled.png'),
  edit: require('../../assets/icons/edit.png'),
  category: require('../../assets/icons/category.png'),
  check: require('../../assets/icons/check.png'),
  services: require('../../assets/icons/services.png'),
  buisness: require('../../assets/icons/buisness.png'),
  search: require('../../assets/icons/search.png'),
  star: require('../../assets/icons/star.png'),
  banner: require('../../assets/images/banner.png'),
};
