export const screens = {
  accounts: 'accounts',
  home: 'home',
  settings: 'settings',
  tab: 'tab',
  profile: 'profile',
  statistics: 'statistics',
  budget: 'Budget',
  transactions: 'transactions',
  login: 'login',
  signUp: 'signUp',
  forgotPassword: 'forgotPassword',
  resetPassword: 'resetPassword',
  OTPScreen: 'OTPScreen',
  profileSetup: 'profileSetup',
  location: 'location',
  success: 'success',
  notification: 'notification',
  ads: 'ads',
  businesses: 'businesses',
  services: 'services',
  serviceDetails: 'serviceDetails',
};
